rcut = 5.99
Ecut = 12
supersampling = 1.4142135623730951

[cutoffs_normal]
Ecut = 12
supersampling = 1.4142135623730951

[cutoffs_high]
Ecut = 12
supersampling = 1.4142135623730951

[cutoffs_low]
Ecut = 12
supersampling = 1.4142135623730951
